apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-0
  labels:
    app: mysql
    podindex: "0"
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  capacity:
   storage: "20Gi" # volume capacity
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "fsf-dal1301e-fz.adn.networklayer.com" # hostname or IP address of the NFS server
    path: "/SL02SV1344071_1/data01/small/mysql-0" # mysql-replica-0 data directory path
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-1
  labels:
    app: mysql
    podindex: "1"
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  capacity:
   storage: "20Gi" # volume capacity
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "fsf-dal1301e-fz.adn.networklayer.com" # hostname or IP address of the NFS server
    path: "/SL02SV1344071_1/data01/small/mysql-1" # mysql-replica-1 data directory path