apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi # volume capacity
  selector:
    matchLabels:
      app: mysql
      podindex: "0"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi # volume capacity
  selector:
    matchLabels:
      app: mysql
      podindex: "1"